### ISSUE TITLE
bug(subd): ToBrep fails due to returned list

### ISSUE THREAD

**Issue by tsvilans** [mcneel/computeclient_py#5]
Line 13 in `SubD.py` fails due to `Util.ComputeFetch(url, args)` returning a list instead of a single object. Sometimes this list has a null object in it as well

Possible fix would be to filter the list and return the only resulting object:
`    response = [Util.DecodeToCommonObject(o) for o in response if o is not None][0]`

**Comment by sbaer** [comment]
@pearswj does your PR at
https://github.com/mcneel/computeclient_py/pull/7
fix this issue?

**Comment by pearswj** [comment]
Yes, it does, though I had to change the endpoint as suggested in #4 to test it.
